- 표본 데이터 불러오기

- 표본 데이터가 정규성 검정하기
    - KSTEST

- 정규표본 이라면 따른다면 T검정, 
    - p-value < 0.05 : 귀무가설 기각, 대립가설이 유효할것'같다.' 
    - p-value >= 0.05 : 대립가설 기각, 귀무가설 채택

In [3]:
# 표본 데이터 불러오기
with open("datas2/성인여성_키_데이터1.txt", "r") as f:
    data = f.read().split('\n')
    # print(data)
    # map(data_type, list_data)
    data = list(map(float, data))
    print(data)
    print(len(data))

[163.94, 162.48, 164.29, 166.3, 162.26, 162.26, 166.43, 164.57, 161.72, 164.05, 161.73, 161.73, 163.36, 158.4, 158.83, 161.51, 160.47, 163.52, 160.71, 159.55, 166.17, 162.28, 162.96, 159.52, 161.55, 163.06, 160.15, 163.66, 161.42, 162.13]
30

In [4]:
#평균값, 표준값 

from scipy import stats
import numpy as np
mean_value = np.mean(data)
std_dev = np.std(data, ddof=0)  # 모집단 표준편차(기본 설정)

mean_value, std_dev

(np.float64(162.36700000000002), np.float64(2.0354559685731335))

# 가설설정
- 귀무가설 : 표본데이터의 평균은 163과 같다.
- 대립가설 : 표본데이터의 평균은 163이 다르다.

## 정규성 검정의 가설
- 귀무가설 : 수집 표본의 데이터는 정규성을 따른다. (정규성의 기본값?)
- 대립가설 : 수집한 표본의 데이터는 정규성을 따르지 않다.

# 표본 데이터 정규성 검정하기
    - 수집한 데이터가 정규분포를 따르는지 검증한다.

In [5]:
#T-test 실행해서 정규성 검정

result = stats.kstest(
    data,
    stats.norm.cdf,
    args=(mean_value, std_dev)
)

print(result)


# statistic, p_value = stats.shapiro(data)

# print(statistic, p_value)

KstestResult(statistic=np.float64(0.08754216181498631), pvalue=np.float64(0.9601287796358491), statistic_location=np.float64(161.42), statistic_sign=np.int8(-1))

In [6]:
#검정하기

print(stats.ttest_1samp(data, 163))

TtestResult(statistic=np.float64(-1.6747153343266057), pvalue=np.float64(0.10474264924733802), df=np.int64(29))

# p-value 가 0.05보다 작음으로 귀무가설을 기각하고 대립가설을 참으로 한다.
# 즉 163과 다르다 라는 결론

독립표본 t 검정

In [7]:
import pandas as pd
import numpy as np
#라이브러리 import

In [8]:
#파일 불러와서 인스턴스화 
df1 = pd.read_csv("datas2/반별_점수_type1.csv", encoding = "euc-kr")
# df1 = pd.read_csv("datas2/반별_점수_type1.csv")
df1.head()

   반  점수
0  A  73
1  A  69
2  A  71
3  A  71
4  A  73

In [9]:
# a반 b반 분리

groupA=df1['점수'].loc[df1['반']=='A'].values
groupB=df1['점수'].loc[df1['반']=='B'].values

print(groupA)
print(groupB)

[73 69 71 71 73 67 73 69 62 74 68 66 70 82 70 65 76 73 58 81]
[63 56 73 61 55 77 75 65 61 55]

In [10]:
# 각 반의 점수 평균
import numpy as np

# A반의 평균과 표준 편차
mean_A = np.mean(groupA)
std_A = np.std(groupA, ddof=1)  # 표본 표준 편차 (ddof=1)

# B반의 평균과 표준 편차
mean_B = np.mean(groupB)
std_B = np.std(groupB, ddof=1)  # 표본 표준 편차 (ddof=1)

# 결과 출력
print(f"A반 평균: {mean_A:.2f}, 표준 편차: {std_A:.2f}")
print(f"B반 평균: {mean_B:.2f}, 표준 편차: {std_B:.2f}")

A반 평균: 70.55, 표준 편차: 5.68
B반 평균: 64.10, 표준 편차: 8.28

In [14]:
# 정리한 데이터의 정규성검정 (pvalue 가 0.05이상인가.)
print(stats.kstest(
  groupA, 
  stats.norm.cdf, 
  args=(np.mean(groupA), np.std(groupA, ddof=0))))

print(stats.kstest(
  groupB, 
  stats.norm.cdf, 
  args=(np.mean(groupB), np.std(groupB, ddof=0))))

KstestResult(statistic=np.float64(0.1290433386337495), pvalue=np.float64(0.8515822805406548), statistic_location=np.float64(73.0), statistic_sign=np.int8(1))
KstestResult(statistic=np.float64(0.17142174723652215), pvalue=np.float64(0.8842512533111235), statistic_location=np.float64(73.0), statistic_sign=np.int8(-1))

정규성 검정
-정규성 검전에서 가설수립
    -대립가설 설정하기 - 두 그룹의 표본데이터는 정규분포을 따른다.
    -귀무가설 설정하기 - 두 그룹의 표본데이터는 정규분포를 따르지않는다.

[해석] pvaplue >= 0  귀마가설을 기각할 필요가없다.
즉 정규성을 따른다고 할수있다.

##등분산성 검정 (개별 확인후 같이 봤을때도 괜찮은지 보기)
- 가설 수립
    - 두 그룹은 분산이 유사하다(등분산성)
    - 두 그룹은 분산이 유사하지않다 (등)

In [16]:
stats.levene(groupA, groupB)

LeveneResult(statistic=np.float64(2.033067087400979), pvalue=np.float64(0.1649640862221014))

[해석]
p-value >= 0.005 두 그룹은 등분산성을 따른다.
p-value < 0.005 두 그룹은 등분산성을 따르지 않는다.

In [20]:
print(stats.ttest_ind(groupA, groupB, equal_var = True))

TtestResult(statistic=np.float64(2.5128526794964134), pvalue=np.float64(0.018010953528937678), df=np.float64(28.0))

독립 표본 t-검정 수행
- 가설수립
    - 귀무가설 - 둘의 표본의 평균은 동일하다. p-value >=0.05
    - 대립가설 - 둘의 표본의 평균은 다르다. p-value <0.05


    즉 2개의 데이터에 대한 확인은 각자 표본을 검사, 검사통과한 표본들을 모아서 서로 같은계열인지 검사, 같은계열(유의미한 표본 이라고 판단)한거를 토대로 원하는바를 확인

In [21]:
df2 = pd.read_csv("datas2/반별_점수_type2.csv", encoding = "euc-kr")
df2.head()

   A반    B반
0  73  63.0
1  69  56.0
2  71  73.0
3  71  61.0
4  73  55.0

In [24]:
group_A = df2['A반'].dropna().values
group_B = df2['B반'].dropna().values
print(group_A)
print(group_B)

[73 69 71 71 73 67 73 69 62 74 68 66 70 82 70 65 76 73 58 81]
[63. 56. 73. 61. 55. 77. 75. 65. 61. 55.]